build:
  image: golang
  commands:
    - go version
    - go get -v -t
    - go build -o sgloadbinary
    - go test -v ./...
    - go get github.com/axw/gocov/gocov
    - go get github.com/mattn/goveralls
    - goveralls -service drone.io -repotoken $COVERALLS_TOKEN
  environment:
    - COVERALLS_TOKEN=$$COVERALLS_TOKEN